In [ ]:
#use if connecting to google drive
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive

##Altering CSVs

In [ ]:
#read csvs into df
import pandas as pd

# Paste the copied path here
data = '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_GradeK.csv'

df = pd.read_csv(data)
df.head()  # Display the first few rows

,State,Total Students,Number_Male,Number_Female,Number_American Indian or Alaska Native,Percent_American Indian or\nAlaska Native,Number_Asian,Percent_Asian,Number_Hispanic or Latino of any race,Percent_Hispanic or Latino of any race,...,Number_Two or more races,Percent_Two or more races,Number_Students With Disabilities Served Under IDEA,Percent_Students With Disabilities Served Under IDEA,Number_Students With Disabilities Served Only Under Section 504,Percent_Students With Disabilities Served Only Under Section 504,Number_English Language Learners,Percent_English Language Learners,Number of Schools,Percent of Schools Reporting
0,"50 states, District of Columbia, and Puerto Rico","92,025","56,225","35,800","1,852",2.0,"1,973",2.1,"20,524",22.3,...,"4,422",4.8,"20,761",22.6,833,0.9,"12,026",13.1,"25,414",100.0
1,Alabama,"2,693","1,686","1,007",35,1.3,21,0.8,254,9.4,...,35,1.3,535,19.9,24,0.9,195,7.2,499,100.0
2,Alaska,96,62,34,52,54.2,0,0.0,2,2.1,...,7,7.3,24,25.0,0,0.0,19,19.8,60,100.0
3,Arizona,"1,439",860,579,105,7.3,19,1.3,647,45.0,...,51,3.5,241,16.7,8,0.6,192,13.3,543,100.0
4,Arkansas,"1,699","1,067",632,12,0.7,8,0.5,211,12.4,...,24,1.4,513,30.2,43,2.5,191,11.2,383,100.0

In [ ]:
#add a start year column and a grade column - helpful for merging later
df["Start year"] = 2017
df["Grade"] = "K"
df.head()

,State,Total Students,Number_Male,Number_Female,Number_American Indian or Alaska Native,Percent_American Indian or\nAlaska Native,Number_Asian,Percent_Asian,Number_Hispanic or Latino of any race,Percent_Hispanic or Latino of any race,...,Number_Students With Disabilities Served Under IDEA,Percent_Students With Disabilities Served Under IDEA,Number_Students With Disabilities Served Only Under Section 504,Percent_Students With Disabilities Served Only Under Section 504,Number_English Language Learners,Percent_English Language Learners,Number of Schools,Percent of Schools Reporting,Start year,Grade
0,"50 states, District of Columbia, and Puerto Rico","92,025","56,225","35,800","1,852",2.0,"1,973",2.1,"20,524",22.3,...,"20,761",22.6,833,0.9,"12,026",13.1,"25,414",100.0,2017,K
1,Alabama,"2,693","1,686","1,007",35,1.3,21,0.8,254,9.4,...,535,19.9,24,0.9,195,7.2,499,100.0,2017,K
2,Alaska,96,62,34,52,54.2,0,0.0,2,2.1,...,24,25.0,0,0.0,19,19.8,60,100.0,2017,K
3,Arizona,"1,439",860,579,105,7.3,19,1.3,647,45.0,...,241,16.7,8,0.6,192,13.3,543,100.0,2017,K
4,Arkansas,"1,699","1,067",632,12,0.7,8,0.5,211,12.4,...,513,30.2,43,2.5,191,11.2,383,100.0,2017,K

In [ ]:
#save resulting csvs
# Save to the same path to overwrite, or a new path to create a copy
save_path = '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_GradeK.csv'
df.to_csv(save_path, index=False)

print(f"File saved successfully to {save_path}")

File saved successfully to /content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_GradeK.csv

##Make one CSV

In [ ]:
data = {
    "State",
    "Total Students",
    "Number_Male",
    "Number_Female",
    "Number_American Indian or Alaska Native",
    "Percent_American Indian or\nAlaska Native",
    "Number_Asian",
    "Percent_Asian",
    "Number_Hispanic or Latino of any race",
    "Percent_Hispanic or Latino of any race",
    "Number_Black or African American",
    "Percent_Black or African American",
    "Number_White",
    "Percent_White",
    "Number_Native Hawaiian or Other Pacific Islander",
    "Percent_Native Hawaiian or Other Pacific Islander",
    "Number_Two or more races",
    "Percent_Two or more races",
    "Number_Students With Disabilities Served Under IDEA",
    "Percent_Students With Disabilities Served Under IDEA",
    "Number_Students With Disabilities Served Only Under Section 504",
    "Percent_Students With Disabilities Served Only Under Section 504",
    "Number_English Language Learners",
    "Percent_English Language Learners",
    "Number of Schools",
    "Percent of Schools Reporting ",
    "Start year",
    "Grade"
}
df_main = pd.DataFrame(data)

# Save to CSV
df_main.to_csv('/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention.csv', index=False)

In [ ]:
import glob

# Find all CSV files in your folder
all_files = glob.glob("/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade*.csv")
print(all_files)

# Combine them all into one
df_list = [pd.read_csv(f) for f in all_files]
final_df = pd.concat(df_list, ignore_index=True)

# Save the final result
final_df.to_csv('/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention.csv', index=False)

['/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_GradeK.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade12.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade11.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade10.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade9.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade8.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade7.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade6.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade5.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade4.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade3.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade2.csv', '/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention_Grade1.csv']

##Cleaning final file

In [ ]:
#remove text rows
edited_file = "/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention.csv"
df = pd.read_csv(edited_file)

df=df.drop([530,531,532,533])
print(df.shape)

df.to_csv(edited_file, index=False)

(689, 28)

In [ ]:
#fixing "1 to 3" for the number/percentage columns
#change these vars and run code
edited_file = "/content/drive/MyDrive/DS3010/csv/2013-2014/2013_2014_Retention.csv"
num_col_name = "Number_English Language Learners"
percent_col_name = "Percent_English Language Learners"

df = pd.read_csv(edited_file)

df["Total Students"] = (
    df["Total Students"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
    .astype(int)
)

mask = (
    (df[num_col_name] == "1 to 3") &
    (df[percent_col_name] != "1 to 3")
)

df.loc[mask, num_col_name] = (
    (
        df.loc[mask, percent_col_name].astype(float) / 100
    ) * df.loc[mask, "Total Students"]
).round().astype(int)

df.to_csv(edited_file, index=False)

In [ ]:
#make everything an integer/float that is not already
edited_file = "/content/drive/MyDrive/DS3010/csv/2015-2016/2015_2016_Retention.csv"

df = pd.read_csv(edited_file)

int_columns = [
    "Total Students",
    "Number_Male",
    "Number_Female",
    "Number_American Indian or Alaska Native",
    "Number_Asian",
    "Number_Hispanic or Latino of any race",
    "Number_Black or African American",
    "Number_White",
    "Number_Native Hawaiian or Other Pacific Islander",
    "Number_Two or more races",
    "Number_Students With Disabilities Served Under IDEA",
    "Number_Students With Disabilities Served Only Under Section 504",
    "Number_English Language Learners",
    "Number of Schools",
    "Start year"
  ]

float_columns = [
    "Percent_American Indian or\nAlaska Native",
    "Percent_Asian",
    "Percent_Hispanic or Latino of any race",
    "Percent_Black or African American",
    "Percent_White",
    "Percent_Native Hawaiian or Other Pacific Islander",
    "Percent_Two or more races",
    "Percent_Students With Disabilities Served Under IDEA",
    "Percent_Students With Disabilities Served Only Under Section 504",
    "Percent_English Language Learners",
    "Percent of Schools Reporting ",
  ]

for col in int_columns:
    df[col] = df[col].astype(str).str.replace(",", "", regex=False).str.strip()

    mask = df[col] != "1 to 3"

    df.loc[mask, col] = df.loc[mask, col].astype(int)

for col in float_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df.to_csv(edited_file, index=False)

ValueError: invalid literal for int() with base 10: '1.0'

In [ ]:
#replace any values in male and female that equal "1 to 3"
import numpy as np

edited_file = "/content/drive/MyDrive/DS3010/csv/2013-2014/2013_2014_Retention.csv"
df = pd.read_csv(edited_file)

male_col = "Number_Male"
female_col = "Number_Female"
total_col = "Total Students"

male_mask = df[male_col] == "1 to 3"
female_mask = df[female_col] == "1 to 3"
both_mask = male_mask & female_mask

# convert needed columns safely
df[total_col] = pd.to_numeric(df[total_col].astype(str).str.replace(",", ""), errors="coerce")
df[male_col] = pd.to_numeric(df[male_col], errors="coerce")
df[female_col] = pd.to_numeric(df[female_col], errors="coerce")

# skip rows where both are "1 to 3"
valid_male = male_mask & ~both_mask
valid_female = female_mask & ~both_mask

# replace male = total - female
df.loc[valid_male, male_col] = df.loc[valid_male, total_col] - df.loc[valid_male, female_col]

# replace female = total - male
df.loc[valid_female, female_col] = df.loc[valid_female, total_col] - df.loc[valid_female, male_col]

df.to_csv(edited_file, index=False)

In [ ]:
edited_file = "/content/drive/MyDrive/DS3010/csv/2013-2014/2013_2014_Retention.csv"

df = pd.read_csv(edited_file)
print(df.head())

           State  Total Students  Number_Male  Number_Female  \
0  United States           94399      55728.0        38671.0
1        Alabama            3011       1822.0         1189.0
2         Alaska              77         43.0           34.0
3        Arizona            1496        875.0          621.0
4       Arkansas            1374        836.0          538.0

   Number_American Indian or Alaska Native  \
0                                     1434
1                                       21
2                                       32
3                                       97
4                                       11

   Percent_American Indian or\nAlaska Native  Number_Asian  Percent_Asian  \
0                                        1.5          1443            1.5
1                                        0.7             7            0.2
2                                       41.6             3            3.9
3                                        6.5            11            0.7
4                                        0.8             7            0.5

   Number_Hispanic or Latino of any race  \
0                                  30733
1                                    232
2                                      5
3                                    727
4                                    155

   Percent_Hispanic or Latino of any race  ...  \
0                                    32.6  ...
1                                     7.7  ...
2                                     6.5  ...
3                                    48.6  ...
4                                    11.3  ...

  Percent_Students With Disabilities Served Under IDEA  \
0                                               16.3
1                                               14.4
2                                               18.2
3                                               14.0
4                                               10.8

   Number_Students With Disabilities Served Only Under Section 504  \
0                                               1838
1                                                  8
2                                                  1
3                                                 34
4                                                 20

   Percent_Students With Disabilities Served Only Under Section 504  \
0                                                1.9
1                                                0.3
2                                                1.3
3                                                2.3
4                                                1.5

   Number_English Language Learners  Percent_English Language Learners  \
0                             17821                               18.9
1                               189                                6.3
2                                35                               45.5
3                               287                               19.2
4                                93                                6.8

   Number of Schools  Percent of Schools Reporting   Start year  Grade  \
0              23622                          100.0        2013      1
1                546                          100.0        2013      1
2                 72                          100.0        2013      1
3                506                          100.0        2013      1
4                326                          100.0        2013      1

   Academic Year
0      2013-2014
1      2013-2014
2      2013-2014
3      2013-2014
4      2013-2014

[5 rows x 29 columns]

In [ ]:
#changing school years to show range of years
import pandas as pd
edited_file = "/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention.csv"

df = pd.read_csv(edited_file)
df["Academic Year"] = "2017-2018"
df.drop(columns="Start year", inplace=True)

df.to_csv(edited_file, index=False)

In [ ]:
#change the Grade column to type string
edited_file = "/content/drive/MyDrive/DS3010/csv/2013-2014/2013_2014_Retention.csv"

df = pd.read_csv(edited_file)
df["Grade"] = df["Grade"].astype(str)

df.to_csv(edited_file, index=False)

In [ ]:
#put NaN for empty rows
import numpy as np

edited_file = "/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention.csv"

df = pd.read_csv(edited_file)
df.loc[52, [
    "Total Students",
    "Number_Male",
    "Number_Female",
    "Number_American Indian or Alaska Native",
    "Percent_American Indian or\nAlaska Native",
    "Number_Asian",
    "Percent_Asian",
    "Number_Hispanic or Latino of any race",
    "Percent_Hispanic or Latino of any race",
    "Number_Black or African American",
    "Percent_Black or African American",
    "Number_White",
    "Percent_White",
    "Number_Native Hawaiian or Other Pacific Islander",
    "Percent_Native Hawaiian or Other Pacific Islander",
    "Number_Two or more races",
    "Percent_Two or more races",
    "Number_Students With Disabilities Served Under IDEA",
    "Percent_Students With Disabilities Served Under IDEA",
    "Number_Students With Disabilities Served Only Under Section 504",
    "Percent_Students With Disabilities Served Only Under Section 504",
    "Number_English Language Learners",
    "Percent_English Language Learners",
    "Number of Schools",
    "Percent of Schools Reporting ",
]] = np.nan

df.to_csv(edited_file, index=False)

##Merging all year CSVs into one

In [ ]:
#/content/drive/MyDrive/DS3010/csv/All_Retention.csv
data = {
    "State",
    "Total Students",
    "Number_Male",
    "Percent_Male",
    "Number_Female",
    "Percent_Female",
    "Number_American Indian or Alaska Native",
    "Percent_American Indian or\nAlaska Native",
    "Number_Asian",
    "Percent_Asian",
    "Number_Hispanic or Latino of any race",
    "Percent_Hispanic or Latino of any race",
    "Number_Black or African American",
    "Percent_Black or African American",
    "Number_White",
    "Percent_White",
    "Number_Native Hawaiian or Other Pacific Islander",
    "Percent_Native Hawaiian or Other Pacific Islander",
    "Number_Two or more races",
    "Percent_Two or more races",
    "Number_Students With Disabilities Served Under IDEA",
    "Percent_Students With Disabilities Served Under IDEA",
    "Number_Students With Disabilities Served Only Under Section 504",
    "Percent_Students With Disabilities Served Only Under Section 504",
    "Number_English Language Learners",
    "Percent_English Language Learners",
    "Number of Schools",
    "Percent of Schools Reporting ",
    "Start year",
    "Grade"
}
df_main = pd.DataFrame(data)

# Save to CSV
df_main.to_csv('/content/drive/MyDrive/DS3010/csv/All_Retention.csv', index=False)

In [ ]:
R2017 = pd.read_csv("/content/drive/MyDrive/DS3010/csv/2017-2018/2017_2018_Retention.csv")
R2015 = pd.read_csv("/content/drive/MyDrive/DS3010/csv/2015-2016/2015_2016_Retention.csv")
R2013 = pd.read_csv("/content/drive/MyDrive/DS3010/csv/2013-2014/2013_2014_Retention.csv")

df_list = [R2013,R2015,R2017]
final_df = pd.concat(df_list, ignore_index=True)

# Save the final result
final_df.to_csv('/content/drive/MyDrive/DS3010/csv/All_Retention.csv', index=False)